from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import *
app=QApplication([])
window=QWidget()
window.setWindowTitle('Degree calculator')
window.resize(350,200)
label_title=QLabel("Вычесление ступеней")
label_a=QLabel("Число:")
label_b=QLabel("Степень:")
label_ans=QLabel("Ответ")
btn_ans=QPushButton('Ответ')
btn_again=QPushButton('Очистить')
label_ask1=QLineEdit()
label_ask2=QLineEdit()
v=QVBoxLayout()
h=QHBoxLayout()
v.addWidget(label_title)
v.addWidget(label_a)
v.addWidget(label_ask1)
v.addWidget(label_b)
v.addWidget(label_ask2)
h.addWidget(btn_ans)
h.addWidget(btn_again)
v.addLayout(h)
v.addWidget(label_ans)
window.setLayout(v)
def ans_dreedge ():
    a=int(label_ask1.text())
    b=int(label_ask2.text())
    c=a**b
    label_ans.setText(str(c))
btn_ans.clicked.connect(ans_dreedge)
def again_ans():
    label_ask1.setText('')
    label_ask2.setText('')
    label_ans.setText('')
btn_again.clicked.connect(again_ans)

window.show()
app.exec()
